version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: go-surgeon
    main: ./cmd/go-surgeon
    binary: go-surgeon
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: go-surgeon
    builds: [go-surgeon]
    name_template: "go-surgeon_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
